export const retentionPolicy = Object.freeze({
  accountInactivityDays: 730,
  textMessageDays: 365,
  mediaMessageDays: 90,
  authSessionHours: 12,
  callSignalHours: 24,
  nativeCallActionMaximumHours: 26,
  callMetadataDays: 90,
  presenceHours: 24,
  pushRegistrationDays: 180,
  familyInvitationValidityDays: 7,
  familyInvitationRecordDays: 90,
  contactRequestPendingDays: 30,
  contactRequestRecordDays: 180,
  gamePendingDays: 30,
  gameRecordDays: 180,
  securityEventDays: 365,
  legalEventDays: 1825,
  rightsRequestRecordDays: 1825,
  erasureTombstoneDays: 30,
  retentionRunDays: 365,
  backupDays: 7,
});
